# Generated by Django 5.2.1 on 2025-06-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_data_access',
            field=models.BooleanField(default=False),
        ),
    ]
