# Generated by Django 5.2.1 on 2025-06-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_allow_data_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
